const Footer = () => {
  return (
    <footer className="bg-neutral-50 dark:bg-neutral-900 h-[50px] px-[50px] flex items-center justify-center">
      <p className="text-neutral-600 dark:text-neutral-400 text-sm">
        GENERATED BY AGENT
      </p>
    </footer>
  )
}

export default Footer